version: "3"

volumes:
  db-data:
  drupal-data:

services:
  mariadb:
    image:  mariadb:10.3
    volumes:
      - "db-data:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "drupal"
      MYSQL_USER: "drupal"
      MYSQL_PASSWORD: "drupal"
    restart: always

  drupal:
    build: .
    volumes:
      - "drupal-data:/var/www/html"
      - "./drupal/modules:/var/www/html/modules"
      - "./drupal/profiles:/var/www/html/profiles"
      - "./drupal/sites:/var/www/html/sites"
      - "./drupal/themes:/var/www/html/themes"
    ports:
      # XDebug
      - "9090:9090"
    environment:
      ENABLE_XDEBUG: "true"
      DRUPAL_DB_HOST: "mariadb"
      DRUPAL_DB_PORT: "5432"
      DRUPAL_DB_NAME: "drupal"
      DRUPAL_DB_USERNAME: "drupal"
      DRUPAL_DB_PASSWORD: "drupal"
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: nginx:stable-alpine
    volumes:
      - "drupal-data:/var/www/html"
      - "./drupal/sites:/var/www/html/sites"
      - "./k8s-helm/drupod/files/nginx/conf.d:/tmp/nginx-conf"
    ports:
      - "10080:80"
    environment:
      SERVER_NAME: "_"
      PHP_FPM_HOST: "drupal"
    command: ["sh", "-c", "envsubst '$$SERVER_NAME $$PHP_FPM_HOST' < /tmp/nginx-conf/drupal.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    depends_on:
      - drupal
    restart: always
