apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-drupal-pvc"
  labels:
    name: "{{ .Release.Name }}-drupal-pvc"
    app.kubernetes.io/name: {{ include "drupod.name" . }}
    helm.sh/chart: {{ include "drupod.chart" . }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: "{{ .Release.Name }}-drupal-pv"
