apiVersion: v1
kind: Secret
metadata:
  name: drupal-secrets
type: Opaque
data:
  drupalDatabasePassword: {{ .Values.drupal.db.password | required ".Values.drupal.db.password is required." | b64enc | quote }}
