apiVersion: v1
kind: Service
metadata:
  name: drupod-db
  labels:
    app.kubernetes.io/name: {{ include "drupod.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ExternalName
{{- if .Values.developMode }}
  externalName: "{{ .Release.Name }}-{{ .Values.mariadb.fullnameOverride }}"
{{- else }}
  externalName: {{ .Values.drupal.db.externalHost | quote }}
{{- end }}
